// <auto-generated />
using System;
using Belloro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Belloro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721132742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Belloro.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Lüks Saatler"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Klasik Saatler"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Spor Saatler"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Premium Saatler"
                        });
                });

            modelBuilder.Entity("Belloro.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Amount = 3450m,
                            CustomerName = "Ahmet Yılmaz",
                            OrderDate = new DateTime(2025, 7, 19, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-0025",
                            ProductId = 1,
                            ProductName = "Belloro Classic Gold",
                            Status = "Tamamlandı"
                        },
                        new
                        {
                            OrderId = 2,
                            Amount = 2780m,
                            CustomerName = "Zeynep Aydın",
                            OrderDate = new DateTime(2025, 7, 20, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-0024",
                            ProductId = 2,
                            ProductName = "Belloro Rose Gold",
                            Status = "İşlemde"
                        },
                        new
                        {
                            OrderId = 3,
                            Amount = 1950m,
                            CustomerName = "Mehmet Kaya",
                            OrderDate = new DateTime(2025, 7, 18, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-0023",
                            ProductId = 3,
                            ProductName = "Belloro Sport",
                            Status = "Kargoda"
                        },
                        new
                        {
                            OrderId = 4,
                            Amount = 2100m,
                            CustomerName = "Ayşe Demir",
                            OrderDate = new DateTime(2025, 7, 16, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-0022",
                            ProductId = 4,
                            ProductName = "Belloro Minimalist",
                            Status = "Tamamlandı"
                        },
                        new
                        {
                            OrderId = 5,
                            Amount = 4280m,
                            CustomerName = "Can Yıldız",
                            OrderDate = new DateTime(2025, 7, 14, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-0021",
                            ProductId = 5,
                            ProductName = "Belloro Automatic",
                            Status = "Tamamlandı"
                        });
                });

            modelBuilder.Entity("Belloro.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Klasik altın kaplama lüks saat",
                            ImageUrl = "/images/products/classic-gold.jpg",
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Belloro Classic Gold",
                            Price = 3450m,
                            SalesCount = 25
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Zarif rose gold kadın saati",
                            ImageUrl = "/images/products/rose-gold.jpg",
                            IsFeatured = true,
                            IsNew = true,
                            Name = "Belloro Rose Gold",
                            Price = 2780m,
                            SalesCount = 18
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "Su geçirmez spor saati",
                            ImageUrl = "/images/products/sport.jpg",
                            IsFeatured = false,
                            IsNew = true,
                            Name = "Belloro Sport",
                            Price = 1950m,
                            SalesCount = 32
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Minimal tasarım klasik saat",
                            ImageUrl = "/images/products/minimalist.jpg",
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Belloro Minimalist",
                            Price = 2100m,
                            SalesCount = 15
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            Description = "Otomatik mekanizmalı premium saat",
                            ImageUrl = "/images/products/automatic.jpg",
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Belloro Automatic",
                            Price = 4280m,
                            SalesCount = 8
                        });
                });

            modelBuilder.Entity("Belloro.Models.Order", b =>
                {
                    b.HasOne("Belloro.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Belloro.Models.Product", b =>
                {
                    b.HasOne("Belloro.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Belloro.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId1");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Belloro.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
